### ISSUE TITLE
Generate sitemap.xml

### ISSUE THREAD

**Issue by SysSn13** [SysSn13/leetcode-rating-predictor#12]
A sitemap.xml file is required for the google search console so that ranking pages can be indexed on google. It should contain all contest ranking pages with the last updated date. Also, It should be automatically updated whenever new contest rankings are added.

**Comment by developer-ishan** [comment]
Do you want to implement it using cron jobs?

**Comment by SysSn13** [comment]
Background jobs are already running using Bull. We can create a new queue for updating the sitemap.xml file. Ref: https://github.com/SysSn13/leetcode-rating-predictor/tree/main/services/job-queues
Whenever a rating prediction job is completed, this new job should run once.
