### ISSUE TITLE
seems cannot find CN users' rank

### ISSUE THREAD

**Issue by Raymond-YP** [SysSn13/leetcode-rating-predictor#30]
I am from LeetCode CN and cannot find myself in the board.

**Comment by caoxingdong** [comment]
The same

**Comment by SysSn13** [comment]
LC predictor fetches rankings from leetcode.com only.

**Comment by caoxingdong** [comment]
Now leetcode.com has updated its ranking, and covered Chinese users.

**Comment by SysSn13** [comment]
Refeteched rankings for today's contest.
