### ISSUE TITLE
The Chinese URL of LeetCode has changed

### ISSUE THREAD

**Issue by silenceneoxw** [SysSn13/leetcode-rating-predictor#37]
Because the Chinese website of LeetCode has changed, the program does not work now.

**Comment by SysSn13** [comment]
It's working fine. The issue was the same as #20.

**Comment by SysSn13** [comment]
Due to the domain name change, the Chrome extension is not working fine for leetcode CN users. We need to change the leetcode CN domain name in the code to fix this.
