### ISSUE TITLE
It seems that leetcode-cn users not supported?

### ISSUE THREAD

**Issue by Deep-Coder-zhui** [SysSn13/leetcode-rating-predictor#42]
In weekly-contest-303，It seems no rating changes display about leetcode-cn users.

**Comment by SysSn13** [comment]
I'm able to see the rating change for all the users. Can you provide some extra info regarding this?

**Comment by Deep-Coder-zhui** [comment]
> I'm able to see the rating change for all the users. Can you provide some extra info regarding this?
for example, a leetcode-cn user  named [guardianemptycoder](https://leetcode.cn/u/guardianemptycoder/), he attempted the weekly-contest-303, but I can't find his rating changes on your leetcode-rating-predicator.

**Comment by Deep-Coder-zhui** [comment]
> I'm able to see the rating change for all the users. Can you provide some extra info regarding this?

for example, a leetcode-cn user named [guardianemptycoder](https://leetcode.cn/u/guardianemptycoder/), he attempted the weekly-contest-303, but I can't find his rating changes on your leetcode-rating-predicator.

**Comment by Deep-Coder-zhui** [comment]
another question, when I finded user named [pi-hua-ting](https://leetcode-cn.com/pi-hua-ting), I could find his related results quickly, but I tried to find "pi-hua", it returned nothing. Will fuzzy search feature be supported someday in the future?

**Comment by SysSn13** [comment]
> > I'm able to see the rating change for all the users. Can you provide some extra info regarding this?
> 
> for example, a leetcode-cn user named [guardianemptycoder](https://leetcode.cn/u/guardianemptycoder/), he attempted the weekly-contest-303, but I can't find his rating changes on your leetcode-rating-predicator.

As for now you have to type case-sensitive exact username to get the rating change. You can find [GuardianEmptyCoder](https://clist.by/account/guardianemptycoder/resource/leetcode.com/)'s rating changes by searching for `GuardianEmptyCoder`.

**Comment by SysSn13** [comment]
> another question, when I finded user named [pi-hua-ting](https://leetcode-cn.com/pi-hua-ting), I could find his related results quickly, but I tried to find "pi-hua", it returned nothing. Will fuzzy search feature be supported someday in the future?

You can create a separate issue for this feature request.  We can implement this in the future.
