### ISSUE TITLE
Predictions are not available

### ISSUE THREAD

**Issue by sachin-0102** [SysSn13/leetcode-rating-predictor#43]
The description says the predictions will be available after 15 minutes of contest or max 1hour in some cases. But there are no predictions till now of weekly contest 308

**Comment by SysSn13** [comment]
The background job worker was down for a few days. I have started a new job worker. So weekly contest ratings will be predicted soon.

**Comment by sachin-0102** [comment]
Do you have to do this after every contest? Or does it happen automatically... Can't see the predictions for today's contest, so just curious...

**Comment by SysSn13** [comment]
@sachin-0102 The process for rating prediction is completely automated. But I need to manually make sure that all the workers are running fine.

**Comment by hritik2002** [comment]
Can't see the predictions for today's weekly contest 307 and yesterday's biweekly contest 86.
Kindly look into the problem : )

**Comment by the-Chain-Warden-thresh** [comment]
It seems that sth wrong with the prediction for **Weekly Contest 312** . Only no more than 150 Chinese users are included in the predicition, all of the users who come from the leetcode-cn.com are missed in the prediction. :( @SysSn13

**Comment by YashJA-dev** [comment]
it's been since more then 12 hours but the prediction of today's contest are still not there can u confirm that how much time will it take

**Comment by SysSn13** [comment]
Working as expected now.
