### ISSUE TITLE
rankings are fetched but predictions not available for biweekly-contest-86

### ISSUE THREAD

**Issue by rjmcmcftw** [SysSn13/leetcode-rating-predictor#45]

**Comment by YashJA-dev** [comment]
that's happening from last 2 contests some times ranking is getting delayed and some time prediction

**Comment by sachin-0102** [comment]
@SysSn13 any updates?

**Comment by SysSn13** [comment]
Again there was a worker issue. The worker was down, so the contest ratings were not fetched and predicted. I fixed the issue, and now it should work normally.
