### ISSUE TITLE
Incorrect predictions for Weekly Contest 309

### ISSUE THREAD

**Issue by TonyTroeff** [SysSn13/leetcode-rating-predictor#47]
I can see that for most of the participants the `Previous rating` and `Expected new rating` fields are empty.
![image](https://user-images.githubusercontent.com/33567383/188304257-d27ef72b-988f-433c-aead-08ebcdf94fd3.png)

Just as a reference - from the Biweekly Contest 86:
![image](https://user-images.githubusercontent.com/33567383/188304362-e6489cb7-6dc7-4c9c-8732-398d872a319a.png)

**Comment by SysSn13** [comment]
It's fixed now.
