### ISSUE TITLE
[ Heroku Alternatives ] Heroku is planning to start shutting down free dynos and data services

### ISSUE THREAD

**Issue by SysSn13** [SysSn13/leetcode-rating-predictor#48]
> Starting November 28, 2022, we plan to stop offering free product plans and plan to start shutting down free dynos and data services. We will be sending out a series of email communications to affected users.

Heroku is planning to stop the free-tier service. Most of our workers and website are running on Heroku free-tier service. If you have any other platform in mind, please share it here.

Read more about it here: https://blog.heroku.com/next-chapter.

**Comment by shadyy41** [comment]
Checkout [render.com](https://render.com/)

**Comment by SysSn13** [comment]
Thank you @shadyy41, for the suggestion. I tried deploying a web app for lcpredictor on this platform and could do it quickly. Here is the URL for the same: https://lcpredictor.onrender.com
We need  Redis to run the background workers. Need to figure out a way to use redis on render.com.

**Comment by kevinjoshi46b** [comment]
Hey @SysSn13,
Redis has a free cloud plan that you can probably use.
Check this out: [https://redis.com/redis-enterprise-cloud/pricing/](https://redis.com/redis-enterprise-cloud/pricing/)

**Comment by SysSn13** [comment]
Hi @kevinjoshi46b, thanks for sharing this. Btw I tried using render.com's free-tier redis service, and it's working fine.

**Comment by krushnadurole** [comment]
@SysSn13 , application is not working. Ratings are not fetched by the application , can you please resolve this issue ? 
Thank You !

**Comment by SysSn13** [comment]
I've deployed the worker on a dedicated server now. It should work from now on. Thanks!
