### ISSUE TITLE
Rank shown is wrong

### ISSUE THREAD

**Issue by susanth29** [SysSn13/leetcode-rating-predictor#5]
In weekly contest 254, my rank is shown as 4581 on your website whereas it is 4603. Presumably, you are loading the list at the exact time of completion of the contest whereas you should wait for a few minutes when the rank list is finalized.

**Comment by SysSn13** [comment]
@susanth29 this is indeed a valid reason for the issue you are facing. We can delay the prediction job by 5-10 minutes or we can schedule two jobs for making predictions, first at the exact time and the second one with some delay. I guess the ranking update on leetcode does not take more than 5-10 minutes.

**Comment by SysSn13** [comment]
For the weekly-contest-254 rankings are re-fetched.

**Comment by susanth29** [comment]
I think 10 minutes should be enough
