### ISSUE TITLE
Update About - within a few minutes of completion of the contest

### ISSUE THREAD

**Issue by manoharreddyporeddy** [SysSn13/leetcode-rating-predictor#50]
Please update About section
to reflect actual behaviour

Been an hour, but no predictions are shown

**About section**

![image](https://user-images.githubusercontent.com/8236389/197374605-cfac6245-3ce7-4c5d-82fc-67424a9c2841.png)

**After 1 hour, no predictions are shown**

![image](https://user-images.githubusercontent.com/8236389/197374706-a96c47bc-5dd2-4135-a210-a4f84395a6f8.png)

**Comment by SysSn13** [comment]
That was due to some issue with the worker. Usually, it doesn't take this much time.
