### ISSUE TITLE
Could not find me in prediction for weekly contest

### ISSUE THREAD

**Issue by zhzho1995** [SysSn13/leetcode-rating-predictor#54]
Hi, my account name is zhzho.

I could not find my account in prediction for weekly contest,  but I could find me in bi-weekly prediction.

Could you please investigate ?

My global rank is 389  in weekly 319 contest. Chinese Nickname: 最佳歌手, account: zhzho

But I am not able to find me in https://lcpredictor.herokuapp.com/contest/weekly-contest-319/ranking/1

**Comment by manoharreddyporeddy** [comment]
Related:
https://github.com/SysSn13/leetcode-rating-predictor/issues/61#issuecomment-1345444008

**Comment by SysSn13** [comment]
@zhzho1995 This has been fixed now. Leetcode.com doesn't show CN region users on rankings pages. We were relying on leetcode.com only for fetching the contest ratings.
