### ISSUE TITLE
[Tutorial Request] LCPredictor offline hwo to use?

### ISSUE THREAD

**Issue by 100jack001** [SysSn13/leetcode-rating-predictor#65]
Since few contests the results are not uploaded and I need to make a request for same.

@SysSn13 Maybe you can make some tutorial that how can we run it on our local machines so. It will be really helpful.

i tried the steps shown in readme file but it's not working for me.
Can you share some screen recording with commentory maybe how to predict rating on local machine.

**Comment by recepkucek** [comment]
I could run on my local. You can download from the following link [biweekly-contest-95](https://easyupload.io/eswks6)

**Comment by wine-fall** [comment]
> I could run on my local. You can download from the following link [biweekly-contest-95](https://easyupload.io/eswks6)
@recepkucek hi, I just downloaded the file and found it is a json file. I don't know how to use that, and how can I get the json file of other contest?

**Comment by wine-fall** [comment]
> I could run on my local. You can download from the following link [biweekly-contest-95](https://easyupload.io/eswks6)

hi @recepkucek , here are what I do

1.  `npm install`
2.  `cp .env.example .env` without change anything
3. `npm run buildAddon`
4.  `brew services start mongodb-community@6.0`: start the mongodb
5. `npm start`

And I saw this:
![image](https://user-images.githubusercontent.com/62830944/211716517-d6003e75-7715-486f-89c9-bc89392d0f4b.png)

Do u notice the message "No **entries** found" ?

Maybe your json file can be one of the **entries** ? But how can I use that and how can I generate a json file by myself?

**Comment by recepkucek** [comment]
There is no json file. I exported from mongodb. 
You must also run  redis.
There are some other issues in code for example leetcode china url has changed to leetcode.cn.
Also you should login bull-board and manually retry the contest prediction job(localhost:/8080/login)

**Comment by geekykant** [comment]
@recepkucek can you share the `weekly-contest-327` results too if possible?
I am having errors with fetching users details  - says too many requests.
```
Failed to fetch: US/mickyor
Failed to fetch: US/underachiever077
Failed to fetch: US/denisgubar
...
```

**Comment by recepkucek** [comment]
Sure. [weekly-contest-327](https://easyupload.io/409zzk)

**Comment by wine-fall** [comment]
hi guys, I just found another predictor website: https://lccn.lbao.site/, which seems work. Hope it help.

**Comment by SysSn13** [comment]
Worker is up now so it should predict the rating from now on. Thanks!
