### ISSUE TITLE
No rating update

### ISSUE THREAD

**Issue by imtiyazMohammed** [SysSn13/leetcode-rating-predictor#66]
Please update the rating for last two contests.

**Comment by manoharreddyporeddy** [comment]
An alternate website:

Last few contests:
- https://lccn.lbao.site/predicted/weekly-contest-329
- https://lccn.lbao.site/predicted/biweekly-contest-96
- https://lccn.lbao.site/predicted/weekly-contest-328
- https://lccn.lbao.site/predicted/weekly-contest-327
- https://lccn.lbao.site/predicted/biweekly-contest-95
- https://lccn.lbao.site/predicted/weekly-contest-326
- https://lccn.lbao.site/predicted/weekly-contest-325
- https://lccn.lbao.site/predicted/biweekly-contest-94

All
- https://lccn.lbao.site/

**Comment by SysSn13** [comment]
Worker is up now.
