### ISSUE TITLE
Rankings fetched but ratings not calculated

### ISSUE THREAD

**Issue by ayushman-sinha** [SysSn13/leetcode-rating-predictor#69]
Rankings fetched for Weekly 328 but ratings yet not predicted.

**Comment by manoharreddyporeddy** [comment]
An alternate website:

Last few contests:
- https://lccn.lbao.site/predicted/weekly-contest-329
- https://lccn.lbao.site/predicted/biweekly-contest-96
- https://lccn.lbao.site/predicted/weekly-contest-328
- https://lccn.lbao.site/predicted/weekly-contest-327
- https://lccn.lbao.site/predicted/biweekly-contest-95
- https://lccn.lbao.site/predicted/weekly-contest-326
- https://lccn.lbao.site/predicted/weekly-contest-325
- https://lccn.lbao.site/predicted/biweekly-contest-94

All
- https://lccn.lbao.site/

**Comment by SysSn13** [comment]
Worker issue. Up now.
