### ISSUE TITLE
Update contest rating for Biweekly and Weekly contests together.

### ISSUE THREAD

**Issue by susanth29** [SysSn13/leetcode-rating-predictor#7]
Your prediction of contest rating is pretty close to the actual one though your site doesn't take into consideration when a user has participated in both the biweekly and weekly contests. It should be solved if you change the `Previous rating` in the weekly contest to the `Expected new rating` in the biweekly contest predicted by your site.
>---
![Biweekly_58](https://user-images.githubusercontent.com/49155218/129481708-b32f1b08-98f2-4838-ae0f-34a790b19b69.png)
>---
![Weekly_253](https://user-images.githubusercontent.com/49155218/129481716-0a50be8f-0479-4a17-890d-fece9eb8cdc4.png)

**Comment by SysSn13** [comment]
@susanth29 I'm not sure which rating Leetcode considers for the weekly contest when there is a biweekly contest. If leetcode uses the new rating after the biweekly contest, this is going to increase the accuracy.

**Comment by susanth29** [comment]
Leetcode uses the new rating after the biweekly contest. After a biweekly and weekly contest, you can verify this if you see the rating change notification on leetcode. Suppose your rating before a biweekly contest is `or` and your rating after both contests is `nr`, then the notification will not be `Your rating has been updated from 'or' to 'nr'` rather it will be `Your rating has been updated from 'mr' to 'nr'` where `mr` is the rating you will get after the biweekly contest and before the weekly contest. In my case, it is `1827 -> biweekly contest 58 -> 1856 -> weekly contest 253 -> 1857`  and you can see the notification here.
![Leetcode_notif](https://user-images.githubusercontent.com/49155218/129515637-7b13663f-ce28-461e-92b1-f91823aff6c7.png)

**Comment by SysSn13** [comment]
Thank you @susanth29 for sharing. This might take some time. I'll update the flow soon.
