### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by RuslansAleksejevs** [SysSn13/leetcode-rating-predictor#71]
Since the results for leetcode contest have not been being predicted already for several months I assume this will not be resolved and the project now is dead. Is it the case? Just want to make it official, so that people do not have empty hopes and do not waste their time.

**Comment by pawx2** [comment]
Yes, I also think this project is dead, because seemly the leetcode changed its contest rules and the method for calculating integral.

**Comment by SysSn13** [comment]
The Leetcode rating predictor is back in action! I've deployed the worker on a good server now.
Head over to the site or use the extension to catch a glimpse of your predicted rating.
Thanks!
