### ISSUE TITLE
Add authentication for bull-board

### ISSUE THREAD

**Issue by SysSn13** [SysSn13/leetcode-rating-predictor#9]
Currently, there is no authentication for accessing the bull-board. [This](https://github.com/felixmosh/bull-board/tree/master/examples/with-express-auth) might be helpful for adding auth with express.

**Comment by VidithM** [comment]
I'm interested in working on this. Where is bull-board being used in the application? Right now I just see an instance of it being exported in background.js, but not being used anywhere.

**Comment by SysSn13** [comment]
It provides a user interface for job queues which are implemented using [bull](https://github.com/OptimalBits/bull). See [bull-board-github](https://github.com/felixmosh/bull-board) to know more.
Enable `BACKGROUND` on your local setup and go to `/bull-board` to see the UI.
